include ../Makefile.inc

P=timers/

all:	
	${GCC} ptimer1.c -lrt -o ptimer1 ${ECHO}ptimer1.c
	${GCC} ptimer2.c -lrt -o ptimer2 ${ECHO}ptimer2.c
	${GCC} ptimer3.c -lrt -o ptimer3 ${ECHO}ptimer3.c
	${GCC} ptimer4.c -lrt -o ptimer4 ${ECHO}ptimer4.c
	${GCC} timer1.c -lrt -o timer1 ${ECHO}timer1.c
	${GCC} timer2.c -lrt -o timer2 ${ECHO}timer2.c
	${GCC} timerex1.c -lrt -o timerex1 ${ECHO}timerex1.c
	${GCC} timerex3.c -lrt -o timerex3 ${ECHO}timerex3.c
	${GCC} timerex.c -lrt -o timerex ${ECHO}timerex.c
clean : 
	${RM} *~ ptimer1 ptimer2 ptimer3 ptimer4 timer1 timer2 timerex1 timerex3 timerex

