include ../Makefile.inc

P=exec/

all:	
	${GCC} exec1.c -o exec1 ${ECHO}exec1.c
	${GCC} exec2.c -o exec2 ${ECHO}exec2.c
	${GCC} exec3.c -o exec3 ${ECHO}exec3.c
	${GCC} exec4.c -o exec4 ${ECHO}exec4.c
	${GCC} exec5.c -o exec5 ${ECHO}exec5.c
	${GCC} test.c -o test ${ECHO}test.c
	${GCC} test1.c -o test1 ${ECHO}test1.c
clean : 
	${RM} exec1 exec2 exec3 exec4 exec5 test1 test  test3 test4

