include ../Makefile.inc

P=multiio/

all:	
	${GCC} multi1.c  -o multi1 ${ECHO}multi1.c
	${GCC} multi2.c  -o multi2 ${ECHO}multi2.c
	${GCC} multi3.c  -o multi3 ${ECHO}multi3.c
	${GCC} poll1.c 	 -o poll1  ${ECHO}poll1
	${GCC} poll2.c 	 -o poll2  ${ECHO}poll2

clean : 
	${RM} *~ pone ptwo mypipe multi1 multi2 multi3 poll1 poll2 

