include ../Makefile.inc

P=proclimit/
all:
	${GCC} pathlim.c -o pathlim ${ECHO}pathlim.c
	${GCC} syslim.c -o syslim ${ECHO}suslim.c
	${GCC} proclimits.c -o proclim ${ECHO}proclimits.c

clean:
	${RM} *~ pathlim syslim proclim
